on: push
jobs:
  run-script:
    runs-on: ubuntu-latest
  first-job:
    runs-on: ubuntu-latest
    steps:
  Checkout-repository:
    uses: actions/checkout@v2
  Setup-Python:
    uses: actions/setup-python@v2
    with:
      python-version: '3.9'
  Install-dependencies:
    run: pip install -r requirements.txt
  Run script:
    python script.py
  setup-chromedriver: 
    uses: nanasess/setup-chromedriver@v2.2.2
