on: push
env:
  email: ${{ secrets.EMAIL }}
  password: ${{ secrets.PASSWORD }}
  PG_USER: ${{ secrets.PG_USER }}
  PG_PASS: ${{ secrets.PG_PASS }}
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python screener.py
      - name: Read data
        run: python convert_df.py
